---
trace:
  id: 1
  next: 2
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: 2
  next: 3, 4
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: 3
  next: 5
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: 4
  next: 6, 7
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: 5
  next:
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: 6
  next:
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: 7
  next:
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  rabbitmq:
    port: 5682
#  zipkin:
#    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
management:
  security:
    enabled: false
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/