---
trace:
  id: '1'
  next: '2'
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: '2'
  next: '3,4'
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: '3'
  next: '5'
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: '4'
  next: '6,7'
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  next: ''
  id: '5'
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  id: '6'
  next: ''
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/
---
trace:
  next: ''
  id: '7'
spring:
  application:
    name: trace-${trace.id}
  profiles: trace-${trace.id}
  zipkin:
    base-url: http://localhost:11031
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: "/api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/swagger.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream"
server:
  port: 1102${trace.id}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11001/eureka/